version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Redstar117390*
      MYSQL_DATABASE: code_challenge
      MYSQL_USER: root
      MYSQL_PASSWORD: Redstar117390*
    ports:
      - "3307:3306"
