#DB_CONFIG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/code_challenge
    username: root
    password: Redstar117390*
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

#APP_CONFIG
  application:
    name: code_challenge

#REDIS_CONFIG
  cache:
    type: redis
    cache-names:
      - cache1
      - cache2
    redis:
      time-to-live: 3600
      cache-null-values: true
  data:
    redis:
      host: localhost
      port: 6379

#ACTUATOR_CONFIG
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: '/admin'
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

#JWT_CONFIG
application:
  security:
    jwt:
      secret-key: ojuupdT7c1dcSYMIS58BHGFswMYDlCJa1cS5hKFRAPuX9rx0Me5obp1W9jhhWmyE
      expiration: 86400000

#LOG_CONFIG
logging:
  level:
    org:
      springframework:
        security: 'DEBUG'

#INFO_CONFIG
info:
  app:
    name: 'User Profile Application'
    description: 'This is an user manager application'
    version: 1.0